services:
  elice_backend:
    container_name: elice_backend
    build:
      dockerfile: Dockerfile
    command: npm run start:dev
    depends_on: 
      - elicelab_database
    env_file:
      - .env

  elicelab_database:
    container_name: elicelab.database
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      default:
        aliases:
          - elicelab_db
